package com.chat.mapper;

import com.chat.model.Video;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface VideoMapper {
    List<Video> findAll(@Param("offset") int offset, @Param("limit") int limit);
    List<Video> findAllNoLimit();
    List<Video> findByType(@Param("type") String type, @Param("offset") int offset, @Param("limit") int limit);
    List<Video> findByCategory(@Param("category") String category, @Param("offset") int offset, @Param("limit") int limit);
    List<Video> findByTypeAndCategory(@Param("type") String type, @Param("category") String category, @Param("offset") int offset, @Param("limit") int limit);
    List<Video> search(@Param("keyword") String keyword, @Param("offset") int offset, @Param("limit") int limit);
    Video findById(@Param("id") Long id);
    int insert(Video video);
    int updateLikeCount(@Param("id") Long id, @Param("delta") int delta);
    int updateViewCount(@Param("id") Long id);
    int addViewCount(@Param("id") Long id, @Param("count") long count);
    int updateCommentCount(@Param("id") Long id, @Param("delta") int delta);
    int countAll();
    int countByType(@Param("type") String type);
    int countByCategory(@Param("category") String category);
    int countByTypeAndCategory(@Param("type") String type, @Param("category") String category);
    int countSearch(@Param("keyword") String keyword);
    List<Video> findByFilePath(@Param("filePath") String filePath);
    List<Video> findByFileName(@Param("fileName") String fileName);
    List<Video> findByFilePathIgnoreCase(@Param("filePath") String filePath);
    List<Video> findByFileNameIgnoreCase(@Param("fileName") String fileName);
    List<String> findCategories();
    int deleteByFilePathPrefix(@Param("prefix") String prefix);
    int deleteById(@Param("id") Long id);
    int updateHashtag(@Param("id") Long id, @Param("hashtag") String hashtag);
    List<String> findAllTags();
    List<Video> findAutoTagged(@Param("offset") int offset, @Param("limit") int limit);
    int countAutoTagged();
    List<String> findPendingTags();
    List<Video> findByPendingTag(@Param("tag") String tag, @Param("offset") int offset, @Param("limit") int limit);
    int countByPendingTag(@Param("tag") String tag);
    int confirmPendingTag(@Param("id") Long id, @Param("tag") String tag);
    int rejectPendingTag(@Param("id") Long id, @Param("tag") String tag);
    int clearPendingHashtag(@Param("id") Long id);
    int renamePendingTag(@Param("oldTag") String oldTag, @Param("newTag") String newTag);
    int updatePendingHashtag(@Param("id") Long id, @Param("pendingHashtag") String pendingHashtag);
    int renameTag(@Param("oldName") String oldName, @Param("newName") String newName);
    int removeTag(@Param("tag") String tag);
    int updateFilePath(@Param("id") Long id, @Param("filePath") String filePath, @Param("thumbPath") String thumbPath, @Param("fileSize") long fileSize);
    int updateFilePathOnly(@Param("id") Long id, @Param("filePath") String filePath);
    int updateTitle(@Param("id") Long id, @Param("title") String title);
    int updateThumbUrl(@Param("id") Long id, @Param("thumbUrl") String thumbUrl);
    int clearAllPendingHashtag();
    int hideByFilePathPrefix(@Param("prefix") String prefix);
    int hideById(@Param("id") Long id);
    int unhideById(@Param("id") Long id);
    int clearCategory(@Param("id") Long id);
    int clearCategoryBulk(@Param("category") String category);
    List<Video> findByCategoryAll(@Param("category") String category);
    List<Video> findNsfw(@Param("offset") int offset, @Param("limit") int limit);
    int countNsfw();
    List<Video> findNsfwByType(@Param("type") String type, @Param("offset") int offset, @Param("limit") int limit);
    int countNsfwByType(@Param("type") String type);
    List<Video> findNsfwByCategory(@Param("category") String category, @Param("offset") int offset, @Param("limit") int limit);
    int countNsfwByCategory(@Param("category") String category);
    List<Video> findNsfwByTypeAndCategory(@Param("type") String type, @Param("category") String category, @Param("offset") int offset, @Param("limit") int limit);
    int countNsfwByTypeAndCategory(@Param("type") String type, @Param("category") String category);
    List<Video> searchNsfw(@Param("keyword") String keyword, @Param("offset") int offset, @Param("limit") int limit);
    int countSearchNsfw(@Param("keyword") String keyword);
    List<Video> findNonNsfw(@Param("offset") int offset, @Param("limit") int limit);
    int countNonNsfw();
    List<Video> findNonNsfwByType(@Param("type") String type, @Param("offset") int offset, @Param("limit") int limit);
    int countNonNsfwByType(@Param("type") String type);
    List<Video> findNonNsfwByCategory(@Param("category") String category, @Param("offset") int offset, @Param("limit") int limit);
    int countNonNsfwByCategory(@Param("category") String category);
    List<Video> findNonNsfwByTypeAndCategory(@Param("type") String type, @Param("category") String category, @Param("offset") int offset, @Param("limit") int limit);
    int countNonNsfwByTypeAndCategory(@Param("type") String type, @Param("category") String category);
    List<Video> searchNonNsfw(@Param("keyword") String keyword, @Param("offset") int offset, @Param("limit") int limit);
    int countSearchNonNsfw(@Param("keyword") String keyword);
    int updateNsfw(@Param("id") Long id, @Param("nsfw") int nsfw, @Param("nsfwType") String nsfwType);
}
